#!/bin/bash -e

set -x

cd $(dirname $0)/..
source ./scripts/set-env-helpers

ENV=${ENV:-${BRANCH_NAME}}
RELEASE_TAG=${RELEASE_TAG:-sha-${GIT_HASH}}

sed -e "s/__TAG__/${RELEASE_TAG}/g" \
  -e "s/__APP_NAME__/${APP_NAME}/g" \
  chart/values-image.yaml.tpl > chart/values-image-${ENV}.yaml
