name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # check docker repository exist
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/static-website-by-nginx
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate helm file
        run: |
          ./scripts/generate-helm-config-files
          ./scripts/push-value-to-remote-repo
        env:
          GIT_API_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          SOURCE_FILE: "chart/values-*.yaml"
          DESTINATION_REPO: "Josaber/gitops-deployment-manifests"
          USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          USER_NAME: ${{ github.actor }}
          DESTINATION_BRANCH: main
